apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-deployment
  labels:
    app: will
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
        - name: will-container
          image: wil42/playground:v2
          ports:
            - containerPort: 8888

---

apiVersion: v1
kind: Service
metadata:
  name: will-service
  labels:
    app: will
spec:
  type : LoadBalancer
  selector:
    app: will
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
